[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "c0df737c86952931f8bd0aa7ea401e488e72f1b4"
libgfortran_version = "5.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "6c8b6836a87fb5b1cd67f2c7f6487322227fb8fd0f5ec5043f049c9c85e672a3"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "637684ff704f654648f20d632cf1b328004cc810"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[COINBLAS.download]]
    sha256 = "57827681b52b3d37db5a51004116bf4b6c4c31d3860b1a0127d067728632fa82"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "02d1673d66a86138e12a3a1b18ac7a469a9d6a71"
libgfortran_version = "3.0.0"
os = "macos"

    [[COINBLAS.download]]
    sha256 = "5100d3edaa7cf97438af2c8f3a0e166aaad255d497f650978aac3003aa429bff"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "19498885999ea53e103615e6fd92c508f8664b9c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "0c244b341370118e4a302c23dc2fe94a38e5aa9f593d87d52d37f6cc24ed027d"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-gnu-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "5fb316c435de43a3405cf8503a2f0398c4c8488a"
libgfortran_version = "4.0.0"
os = "macos"

    [[COINBLAS.download]]
    sha256 = "185082ace08822e5e860c973c91acfb7751145b73bb74d990c46fcc06d55af97"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "2dc7fb189bf044d49783436d7aa5f3d42093c028"
libgfortran_version = "5.0.0"
os = "macos"

    [[COINBLAS.download]]
    sha256 = "1b55214db0ceea5ee59dedc7dd614d640875aeefcafa1ffad639ba1d9b09adce"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "21fd1240f155b3ee6c037e47cf59b93e1fbb687b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "4c1c3db3b948bad83bfc2cffe91d2228499929fd8c783b040bc9031b183b6427"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "83db669a9c3a48a2d4e60f920dd4a8d40ba99de3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "77662c35d77969caef495bf7bb03dbd67e9a0b870c688885bac5cf9a43ee6b29"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-gnu-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "70ba342f3964281095243c43bf615700066847f8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "dde79f9b6d45fbd3503b72d7eb8f0dc890395b7166d3903d84665bca6b6c3244"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-musl-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "071e9c0adccea68d78fca9473515eb4de7c6f410"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "54b68582bfb03a0865c090e232564750dfc800e494032994d5a10f8532c91efc"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "0ef9199037b7d1333de35e0379d627cc4e380021"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "c23e46ad04bd1e396693cdb0686d9451dff7d1c2096e152b82363456ef55b5ed"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "81a0fccf16d8f6a0f603bf4c16e44222a3ef15f3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "2eef19d89da778f26713788a8df7b3ee65502161ac6a31a2c3151c7fd4dd051d"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-gnu-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "7f50290a8c7fa76db791a29bc42795ccd04345a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "6d62834cce1eea669427e7d75464a4dc7b9f8d8ecc1cf56468e4219794b73473"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "35607191045227ee9fd05893c812aee4d5876dc0"
libgfortran_version = "4.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "2c94b7c42c25c5c627f6bce406f57bac0dfff221b3bc99d1814fd4d5d28f4b56"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-w64-mingw32-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "19f2280b5cd273d01eaa88a1da16046b9590783e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "19ad062d7435f877cecb500eeef4becf1f4b366888374063af66e51d7c62c00d"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "e3611d1765f0eb94b176a268f997c6e3cddd41e7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "f74713a01afb6243af2a505b0ad5aa3612c65c41c4f9488b2fb0b103984340cc"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-musl-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "4590142233c9145e3e6f0d99d2b5f9af7e868d7c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "c91c0adadf41dd76d1fca1d52cad6183fd15304d75d7433c207fec240b7be8e2"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-gnu-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "bceb0966478243c99d40260df609243e96443f79"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "65156c0b3b4ed87539602658c3664d205a96aa65f8cbc51c080f550fd8a5c050"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "e446e61f333d89bc309ba7b17d6b37703b642e0c"
libgfortran_version = "5.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "eecdd8fd65a067a08b26fbc280475c1fd725914e8f6d46f7ab639b86646cb19b"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-w64-mingw32-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "e2b5510807fd3366a64b0588dd78c86f2755ceb2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "aff7dbde2895dbc5a07b8efb852d9a818e4ddcf75b947b4171eb9f8c27b95636"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-gnu-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "2c8ce1768abbd9635f338e9f811b042ee5834038"
libgfortran_version = "3.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "8613edb7f8a4ac7ed569b443aac4a433e70d343955d8f2b362b96ff06d1c5f0f"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-w64-mingw32-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "3da860a0ac2981bfbc6e6b6649d6b3a57779ea71"
libgfortran_version = "4.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "ac1de9bc55e3233d354249bfee42261b18bead8d53be3bb3ada9e5bed098d81b"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "e9c4e0812be2e398c65f54b9e07e57c6cb6bbb25"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[COINBLAS.download]]
    sha256 = "ab0ef4a096b62206a90386389c608e986399523e5a3fc28feb94c8e9475052b3"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "5ac32cce2ee01db48d4595698ae70eebc7312b1d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "779ae8b56df4d4234ea07bcf4c3f908d26d6b59aa10467102d2acc5be03e7861"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-gnu-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "8210669d2b5173243a43076499c094718076ab3e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "8d9908e93efa7a6cadf89d10466cef2a6f43dd6d218a69517e7fbff0332612c8"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-musl-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "e19d3749a25f0b6d914966a15e598c444bbbad1c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "8aeded2c0fb39e448a2478dc1906d2f3302f31034e43bbeb122bddb9f4df018a"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-musl-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "16bc6e2e6bc6bebfd6a0eb20497b77935126441d"
libgfortran_version = "3.0.0"
os = "windows"

    [[COINBLAS.download]]
    sha256 = "6b9095a4c85f419ce253cf3de83892c60b890cfb198b81f79393d3dfe903abcd"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "b48f40c63b0bc223ba5195a2fa7e327d47367716"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "82d5252941f394f73d539c8c91a229fa34634d986e13dbdea241d46f957581cf"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "b9b67512a9e5d536fddc061b7d1f7682a473b802"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "2206914009847f4e0a7fdff6c8b07380e33f33f7741621f0fe0f4eaea273c05c"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-gnu-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "4609c1cacf02d7b86b318e6bb5a18780095befa1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "34290f77d25bc16649b8a18c71d7606168a21622dcf947623033e4d8e36dbdaa"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-linux-musl-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "874724669f17ecf2c75d9bbf23403f83cb06ae10"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "df0b5018a9b0411e059ef7957ec5f2eff7fc290b0ba1e1e010da9bb26e07a5ea"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-musl-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "df00d9fdc41648a543b10a7328bc99747fe0a2eb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "a0ff787ccf8e588dd1e5e69fe75b1a9fe1c0cf9d335694aee9762215284a5006"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-gnu-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "b4acf08152d05afa3c8ccd250b27ad9f3608a7e2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "0cf8836a94a2cea85fcee7b91ef82105f55895b90b4e9179d1e2ad43dc4501e2"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-gnu-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "x86_64"
git-tree-sha1 = "a350e21d48fc0105ac7c7fbfe069c6919550e0aa"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[COINBLAS.download]]
    sha256 = "d59db31ba191551c48485f82aa3f73bf1b6299cd71748bb6d0f362740213b0a1"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "e9263e261597bb5f16c9bff0b3b824191a392776"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "996ff682d95891d64b77f636aa7f99e5c1b7cc9aebde7501d7dc3438afd4e199"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-musl-libgfortran3.tar.gz"
[[COINBLAS]]
arch = "armv7l"
git-tree-sha1 = "01a8da35091ed9760d13acc1f84ea3dfc2a28119"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "41e70df1732151676c742a9940e07acd3de83660f5ad3f6e1fdfd249b93ebd73"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "i686"
git-tree-sha1 = "efc403d6bf9fa4dce784c9c49f8bdf03b8d4dbe4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "3097eb2bbf224940271acac85d22c4ddf05a309a06a790a8b2d5b9399bda9387"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.i686-linux-musl-libgfortran4.tar.gz"
[[COINBLAS]]
arch = "aarch64"
git-tree-sha1 = "79477a9220c135e691e06265e0d4a5acc79b99be"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "8f474c2eea5a82f0f47e28ab075bd5867a0cab3a778dae47c8e14e0d23e3c184"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.aarch64-linux-musl-libgfortran5.tar.gz"
[[COINBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "a55a99f3e98455c6d09de1e274fd1dc104d3f574"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[COINBLAS.download]]
    sha256 = "4cf454b1e06659738a152c52d5ecc5fa56bb458f4179fabc3a8c4f1c59ae1ca4"
    url = "https://github.com/JuliaBinaryWrappers/COINBLAS_jll.jl/releases/download/COINBLAS-v1.4.8+0/COINBLAS.v1.4.8.powerpc64le-linux-gnu-libgfortran4.tar.gz"
